[package]
name = "omw-pump"
version = "0.1.0"
description = "Solana memecoin platform that helps reduce rugpulls by implementing a ton of security features and adding new features to the website will be as frequent as new updated information is recognized "
edition = "2025"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []